services:
  postgres:
    image: postgres:16
    container_name: squabblin-postgres
    environment:
      POSTGRES_USER: goblin
      POSTGRES_PASSWORD: goblin
      POSTGRES_DB: squabblin
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
